### ISSUE TITLE
How can install the package at N3200pro?

### ISSUE THREAD

**Issue by zonky2** [BrianGilbert/thecus-btsync#1]
How can install the package at N3200pro?

Thanks

**Comment by BrianGilbert** [comment]
I'm not sure what CPU that model has, but you'd best try installing the latest release at http://thecusunderground.com/module/bittorrent-sync

If that doesn't work you'll need to SSH into your NAS and give me the result you see when running this command

```
uname -m
```

**Comment by zonky2** [comment]
Hi Brian,

it´s not possible to install the .mod file - the admin backend show the follow information. "Installation des Moduls fehlgeschlagen, da NAS-Typ nicht passt." like in english: "Installation of the module failed because NAS type does not match."

the command uname -m send "i686"

**Comment by BrianGilbert** [comment]
I've switched to a Synology now so no longer supporting this code
